### ISSUE TITLE
Content is displayed for the first time

### ISSUE THREAD

**Issue by ivignan** [AdTechMedia/drupal-module#11]
When content is displayed for the first time, ATM plugin will call ATM platform to get locked version of the content and store it in db, ATM-specific table

**Comment by eistrati** [comment]
Replicate the following UI and UX: https://dev-atm-wp-v46.pantheonsite.io/2017/01/05/how-to-beat-adblocking-without-hurting-the-user-experience/

**Comment by eistrati** [comment]
Will provide updated requirements in different tickets.
