### ISSUE TITLE
Plugin administration view

### ISSUE THREAD

**Issue by ivignan** [AdTechMedia/drupal-module#17]
API key + REGENERATE button (first time - auto generated)
Country (e.g. United States)
NOTE: html select
Revenue method (e.g. advertising + micropayments, advertising, micropayments)
NOTE: html select
Email address + ACTIVATE button
Content pricing (e.g. 29 cents) + currency (depends on country)
Note: HTML input + select
Content paywall (e.g. 3 transactions, 100 currency units)
Note: HTML input + select
Content preview (e.g. 3 paragraphs, 100 words)
Note: HTML input + select
Content unlocking algorithm (e.g. blur, scramble, keywords, blur + scramble)
NOTE: html select
DNS access (let’s start with AWS keys to Route 53)

**Comment by eistrati** [comment]
Replicate the following UI and UX: https://github.com/AdTechMedia/wordpress-plugin/blob/master/src/views/admin.php

**Comment by eistrati** [comment]
Will provide updated requirements in different tickets.
