### ISSUE TITLE
Create visual form for edit widget layout like in WordPress

### ISSUE THREAD

**Issue by eistrati** [AdTechMedia/drupal-module#26]

**Comment by avozicov** [comment]
The following discrepancies between "WordPress" and "Drupal" edit widget layout form were found:
- "Drupal" - Missing "Reset to Defaul Settings" button for Drupal

_Please refer to attachment for more details:_ 
**WordPress**
<img width="1091" alt="wordpress missing -reset to defaul settings- button for drupal" src="https://cloud.githubusercontent.com/assets/12330493/23997196/04d27184-0a59-11e7-8c6a-f317e77a18bc.png">
**Drupal**
<img width="1232" alt="drupal missing -reset to defaul settings- button for drupal" src="https://cloud.githubusercontent.com/assets/12330493/23997197/04d2ca3a-0a59-11e7-9f4f-d3183c128468.png">

**Comment by azzaromax** [comment]
this functionality was not part of our project

**Comment by avozicov** [comment]
Discrepancy was added as an enhancement in the following task:
https://github.com/AdTechMedia/drupal-module/issues/61
