### ISSUE TITLE
Widget styles are broken

### ISSUE THREAD

**Issue by ghost** [AdTechMedia/drupal-module#32]
Please refer to attachments:

<img width="197" alt="screen shot 2017-01-25 at 10 12 01 am" src="https://cloud.githubusercontent.com/assets/10956412/22291758/a53b0534-e310-11e6-905b-0d21afea4306.png">

<img width="1280" alt="screen shot 2017-01-25 at 3 05 37 pm" src="https://cloud.githubusercontent.com/assets/10956412/22291571/c0a5447a-e30f-11e6-9109-c0048367b4c1.png">

<img width="1280" alt="screen shot 2017-01-25 at 3 00 30 pm" src="https://cloud.githubusercontent.com/assets/10956412/22291563/b4a640fc-e30f-11e6-9bee-af0d45c85f5e.png">

**Comment by azzaromax** [comment]
fixed
