### ISSUE TITLE
Widget is not fixated to the page

### ISSUE THREAD

**Issue by ghost** [AdTechMedia/drupal-module#33]
Please refer to attachment: make sure that widget is fixated to the page

![ezgif com-video-to-gif 2](https://cloud.githubusercontent.com/assets/10956412/22291852/17e045f4-e311-11e6-8745-1aec85450b57.gif)

**Comment by alex-histev** [comment]
@dsasov please clarify rules when widget must appear. We take demo on WP as example. Ref link: https://dev-atm-wp-v46.pantheonsite.io/2017/01/05/why-just-blocking-the-adblockers-doesnt-work/

On our stage - http://dev-wise-atm-drupal-8.pantheonsite.io/node/1 widget has similar behavior. One issue that I see in our realization that widget is not a fixed div on page. Please check http://dev-wise-atm-drupal-8.pantheonsite.io/node/1 again and give more detailed explanation what's wrong with it. Thank you.

**Comment by ghost** [comment]
@alex-histev Widget being not a fixed div is the root cause of the current behavior, please refer to updated description representing this issue.
