### ISSUE TITLE
Unnecessary empty button between [Setup and Pay] and [Show Ad]

### ISSUE THREAD

**Issue by ghost** [AdTechMedia/drupal-module#34]
See attached: there is an empty button between [Setup and Pay] and [Show Ad] in "Pay" view

<img width="621" alt="screen shot 2017-01-25 at 10 55 53 am" src="https://cloud.githubusercontent.com/assets/10956412/22291906/65b47f70-e311-11e6-830d-0cb91c86aac5.png">

**Comment by alex-histev** [comment]
Hi @dsasov could you give more info about situation when this bug appear? In that browser? Which actions you did before. Please describe it in details because we can't reproduce it. Thank you

**Comment by ghost** [comment]
@alex-histev Bug reproduces in MacOS in all browsers:
in Chrome version 55.0.2883.95
in Safari version 10.0.2 
in Firefox version 50.1.0

Steps to reproduce:
1) Click on [Pledge] button in the first article
2) Open the second article and click on [Pledge] as well
3) Open the third article and click on "Setup payment method now." link

See attached: 
<img width="1278" alt="screen shot 2017-01-27 at 11 02 54 am" src="https://cloud.githubusercontent.com/assets/10956412/22365448/33df192c-e480-11e6-9d77-2a2d1f8a7d59.png">

**Comment by azzaromax** [comment]
Fixed
http://prntscr.com/eetvxn
