### ISSUE TITLE
Module is not displayed on the article page after enabling

### ISSUE THREAD

**Issue by ghost** [AdTechMedia/drupal-module#45]
1) Install AdTechMedia module
2) Enable it on the [Extend] Drupal page
3) Open any article

Actual result: module is not displayed on the article page. It becomes displayed only after clicking on [Save] button in the "General Configuration" area (refer to the attachment)

@eistrati: is this the expected behavior? Actually this is a discrepancy between Drupal module and Wordpress plugin. In Wordpress -> plugin appears on the post page right after enabling.

<img width="638" alt="screen shot 2017-02-27 at 11 47 45 am" src="https://cloud.githubusercontent.com/assets/10956412/23356467/94497288-fce2-11e6-87dd-9d8f37f6e429.png">

**Comment by avozicov** [comment]
blocked by https://github.com/AdTechMedia/drupal-module/issues/60

**Comment by avozicov** [comment]
_Note:
Additional step are required:_
- Sticky option should be disabled (otherwise content is scrambled, but ATM Plugin is not visible on content page)
