### ISSUE TITLE
Content configuration changes are not applied to the module

### ISSUE THREAD

**Issue by ghost** [AdTechMedia/drupal-module#46]
1) Install AdTechMedia module and enable it
2) Open its configuration page
3) Change any value in 'Content Configuration' area(e.g. Content pricing from `5` to `4`) and click on [Save] button (refer to the attachment)
4) Open any article

Expected result: updated price(`4`) should be displayed
Actual result: old default price(`5`) is still displayed
Note: `atm.min.js` file is not updating after saving 'Content configuration' which looks to be the root cause of the issue.
Bug reproduces for all values in 'Content configuration' area.

<img width="637" alt="screen shot 2017-02-27 at 12 04 00 pm" src="https://cloud.githubusercontent.com/assets/10956412/23357060/db26b3bc-fce4-11e6-90db-2bc7ff07977c.png">

**Comment by azzaromax** [comment]
Fixed
