### ISSUE TITLE
Do not save non-existing variables in Templates Management

### ISSUE THREAD

**Issue by ghost** [AdTechMedia/drupal-module#47]
1) Install AdTechMedia module and enable it
2) Open its configuration page
3) Change any variable in Templates Management (e.g. `{user}` to `{users}`) (refer to the attachment)
4) Click on [Save] button

Expected result: changes should not be saved and error message should be displayed: `Variable {users} is not defined.`
Actual result: changes become saved with non-existing variable and error is displayed in console: `Uncaught Error: Missing rendition component 'users' for option 'body-welcome' in template 'pledgeComponent'`
Please apply the fix to all templates: Pledge/Pay/Refund/Other

<img width="1280" alt="screen_shot_2017-02-27_at_1_55_20_pm" src="https://cloud.githubusercontent.com/assets/10956412/23360526/81380724-fcf4-11e6-85df-ce80698d197c.png">

**Comment by avozicov** [comment]
There is an issue in actual implementation. 
(please refer to the attachment)

BUG: 

- Wrong trigger method for notification message when invalid form data is added 

_Issue details:_

- When not valid data was introduced to the form, notification message is triggered for each character.
- As a result multiply notification messages are displayed. 

_Improvement:_

- In case when not valid data was introduced in the form, notification message should be triggered only when user clicks on "Save" button in the related modal.
- Field with invalid data should be highlighted and message should disappears by the click on related field.
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/12330493/23711607/ff472fba-0428-11e7-8898-b84799d448d3.gif)
