### ISSUE TITLE
Empty little button next to [Setup and Pay] button

### ISSUE THREAD

**Issue by ghost** [AdTechMedia/drupal-module#48]
Prerequisites: there must be at least 3 articles to reproduce this issue.

1) Install AdTechMedia module, enable it
2) Click on [Pledge] button in two articles and open the third one
3) Click on "Setup payment method now" link
4) Input all the fields with valid data

Please refer to the attachment: there's an empty button next to [Setup and Pay] button, please remove it.

<img width="1178" alt="screen shot 2017-02-27 at 4 44 01 pm" src="https://cloud.githubusercontent.com/assets/10956412/23366285/dba722a2-fd0e-11e6-85ef-4cbd2e1cdedb.png">

**Comment by azzaromax** [comment]
Tag button hasn't class atm-arrow. This code generating on the atm server.

**Comment by ghost** [comment]
Dependent on https://github.com/MitocGroup/atm/issues/828

**Comment by avozicov** [comment]
blocked by #60
