### ISSUE TITLE
[Change to Amazon/PayPal/card] dropdown options are not clickable

### ISSUE THREAD

**Issue by ghost** [AdTechMedia/drupal-module#49]
Prerequisites: make sure that "Sticky" option in "Overall position and styling" area is unchecked.

1) Open the Pay view
2) Expand [Pay] button dropdown

Please refer to the attachment: options are not clickable because of the Drupal header which overlaps them.

<img width="1280" alt="screen shot 2017-02-27 at 5 39 58 pm" src="https://cloud.githubusercontent.com/assets/10956412/23370598/dca4259c-fd1d-11e6-85df-98def952f8d9.png">

**Comment by azzaromax** [comment]
http://prntscr.com/eesush
All is good

**Comment by avozicov** [comment]
@azzaromax To add more details for this issue I would like to point that drop-down menu is visible, but non of available options (PayPal / Amazon Payments) are clickable and as result non of options can be chosen.

**Comment by ghost** [comment]
Please refer to the attachment: dropdown options are working fine(are clickable) on ATM demo page:

![ezgif com-video-to-gif 4](https://cloud.githubusercontent.com/assets/10956412/23665979/ac41ce36-0362-11e7-94ec-6c40a9447b51.gif)

But in Drupal module they are not clickable:

![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/10956412/23666121/fb276236-0362-11e7-8b16-345ab5a417bb.gif)
