### ISSUE TITLE
ATM module is not displaying on content page 

### ISSUE THREAD

**Issue by avozicov** [AdTechMedia/drupal-module#60]
_Pre-requisites :_ 
- user must have drupal module installed and configured on a local 
- user must have at least one article on content page 
- ATM module should be installed on drupal and should be applied on article from admin page

_Stets to reproduce :_ 
- Navigate to content page and check ATM module appearance 

_BUG :_ 
- ATM module is not displaying on content page 

_Issue details :_  
- "atm.min.js" file and "atm" folder is missing in "drupal/sites/default/files/"
- Once I have manually added "atm" folder to the "drupal/sites/default/files/" an error appeared (attachment 2)
- Bug is reproducing on two different machines with Mac Os 
- Bug is reproducing on different local server configuration (MAMP) 

_Please refer to attachment for more details :_  

<img width="1280" alt="screen shot 2017-03-14 at 17 46 11" src="https://cloud.githubusercontent.com/assets/12330493/23914574/099d9e98-08ef-11e7-8aef-1b8bf19ed710.png">

<img width="1280" alt="screen shot 2017-03-14 at 19 46 46" src="https://cloud.githubusercontent.com/assets/12330493/23914565/fcc34236-08ee-11e7-9c7f-9690cc0df250.png">

**Comment by alex-histev** [comment]
@avozicov please post screenshot of page in Drupal with info about configuration. It's in Reports -> Status Report. Looks like you have issue with permissions for upload files folder.

**Comment by avozicov** [comment]
@alex-histev 
Please refer to the attachment for info about configuration from "Status Report" page.
<img width="1280" alt="screen shot 2017-03-15 at 15 54 49" src="https://cloud.githubusercontent.com/assets/12330493/23951776/eaf1d29e-0997-11e7-9b2f-f3a65272a9c8.png">

**Comment by alex-histev** [comment]
I confirm that we have issue with installing module. 

During install process module can't create subdir atm in default/files folder.
![atm-drupal8-install-error](https://cloud.githubusercontent.com/assets/20904734/24006011/2d7dcd58-0a73-11e7-83e6-b9f80bfe8d18.png)

**Comment by avozicov** [comment]
_Status :_ 
I have performed test on local machine with updated code from dev branch
Test = FAILED with the same behavior as described in issue description 

_Test environment :_ 

- MacOs Sierra 
- Chrome Version 57.0.2987
- Safari Version 10.0.3 (12602.4.8)

**Comment by avozicov** [comment]
Bug is reproducing in new dev build with the same behavior as described in the task description

**Comment by avozicov** [comment]
Bug was tested on "Prod Release 2017/03/27" build.
Test = PASSED
