### ISSUE TITLE
Prod API is used when accessing module from localhost domain

### ISSUE THREAD

**Issue by avozicov** [AdTechMedia/drupal-module#67]
_Pre-requisites:_
- ATM Plugin should be installed and activated
- At least one content should be created and Plugin should be applied 
- "Content paywall" value should be exceeded and Setup Payment view should be active

_Steps to reproduce:_
1. Navigate to content page 
2. Click on "Pay with Card" as payment method and fill the fields with test card 
3. Click on "Setup and pay" button 

_BUG:_
- Payment is declined because Prod API is used for process the request 

_Issue Details:_ 
- Notification message with the text is displayed:
"Your card was declined. Your request was in live mode, but used a known test card."

_Improvement:_
- API should be automatically switched to Dev API when module is accessed from localhost 

_Please refer to attachment for more details:_
<img width="1280" alt="screen shot 2017-03-28 at 13 43 32" src="https://cloud.githubusercontent.com/assets/12330493/24401653/df356cc4-13bd-11e7-84dc-98cce07299e8.png">

**Comment by ivignan** [comment]
It is ok for now
