### ISSUE TITLE
"Content Preview" settings are applied with wrong values

### ISSUE THREAD

**Issue by avozicov** [AdTechMedia/drupal-module#68]
_Pre-requisites:_
- ATM Plugin should be installed and activated
- At least one content should be created and Plugin should be applied
- "Content preview" value should be set at 3 words

_Steps to reproduce:_
- Navigate to content page
- Click on "Pay with Card" as payment method and fill the fields with test card
- Click on "Setup and pay" button

_BUG:_

- Content Preview settings are applied with wrong values

_Issue details:_
- One word of content is visible, expected visible content is set to 3 words
- Bug is reproducing to the "Paragraph" type as well

_Please review to attachments for more details:_
<img width="601" alt="screen shot 2017-03-28 at 14 37 30" src="https://cloud.githubusercontent.com/assets/12330493/24403112/1bd0f2c4-13c4-11e7-9056-8b16d9c861a3.png">
<img width="1280" alt="screen shot 2017-03-28 at 14 34 38" src="https://cloud.githubusercontent.com/assets/12330493/24403113/1bd1df18-13c4-11e7-8c0e-750f9b794d44.png">

**Comment by avozicov** [comment]
@eistrati @ivignan 
Actual Result: 
- "2 paragraphs" is set as a default value for "Content Preview" field, but changes are not applied until user clicks on "Save" button on "configuration" page 

Please let me know if actual implementation can be considered valid? 
I will update the issue status based on your response.

**Comment by ivignan** [comment]
@avozicov Sorry, your comment is not clear for me. Are the Content Preview settings applied with correct values for admin users or NOT ?

**Comment by avozicov** [comment]
@ivignan 
"Content Preview" settings become applied with correct values **only** after performing additional "Save" action on "config" page 

_Actual Result:_
_[config page]_ Default "Content Preview" settings = 2 paragraphs
_[content page]_ Only 1 paragraph is available (unscrambled, not blurred) 

_Expected result:_
_[content page]_ According to "Content Preview" default settings - 2 paragraphs should be available (unscrambled, not blurred)

**Comment by ivignan** [comment]
@avozicov do you have to Click Save twice?

**Comment by avozicov** [comment]
@ivignan 
Here is the test situation described step-by-step in right order to reproduce the issue: 
1. User **installs** AdTechMedia Plugin 
2. User is navigating to "AdTechMedia" Plugin "Configuration" page just to **see** what **settings** and **values** are already **set by default**  - (no **Save** action here)
- at this point **default** "Content Preview" **settings** = **2** paragraphs
3.  User is **navigating** to "Content" page **to review** "AdTechMedia" **Plugin behavior** 
- at this point only **1** content paragraph is available (unscrambled, not blurred) 
- but we **expect 2** paragraphs to be available (as already **set in default plugin settings**)
4. User is **repeating** step 2 and "Clicks" on "**Save**" button for "Content Preview" field 
5. User is **repeating** step 3 and **only** now **2** paragraphs are **available** (unscrambled, not blurred) 

This means that user is **required** to click on "**Save**" button so the **default parameters**  for "Content Preview" field become **applied**
