### ISSUE TITLE
"Text align" option can not be applied on "Templates Management" module

### ISSUE THREAD

**Issue by avozicov** [AdTechMedia/drupal-module#71]
_Steps to reproduce:_ 
1. Navigate to "ATM Plugin Configuration/Templates Management" page 
2. Change "text align" option and Save changes

_BUG:_ 
"Text align" option can not be applied

_Please refer to attachment for more details:_
<img width="881" alt="screen shot 2017-03-29 at 12 34 54" src="https://cloud.githubusercontent.com/assets/12330493/24448235/2e32b386-147c-11e7-9f44-e3ff9eb9d772.png">

**Comment by azzaromax** [comment]
Text wrapped in a span tag and all style properties are applying to it, but it does not support alignment

**Comment by avozicov** [comment]
Task will be tested once the requirements will be clarified.
(Details were sent to Eugene, Igor in "ATM Drupal Requirements" email)

**Comment by ivignan** [comment]
@azzaromax please remove text align from templates and keep only 2 items in the row.
